<?php

namespace AppBundle\Repository;

/**
 * FSACommentActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FSACommentActionRepository extends \Doctrine\ORM\EntityRepository
{
}
