<?php

namespace AppBundle\Repository;

/**
 * FSAPlanActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FSAPlanActionRepository extends \Doctrine\ORM\EntityRepository
{
}
