<?php

namespace AppBundle\Repository;

/**
 * FSAResponsableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FSAResponsableRepository extends \Doctrine\ORM\EntityRepository
{
}
