<?php

namespace AppBundle\Repository;

/**
 * FSAStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FSAStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
