<?php

namespace AppBundle\Repository;

/**
 * note2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class note2Repository extends \Doctrine\ORM\EntityRepository
{
}
